name: android

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version information (e.g., 1.20.0)"
        required: true

permissions:
  contents: write

env:
  ONNXRUNTIME_VERSION:
    |- # Enter release tag name or version name in workflow_dispatch. Appropriate version if not specified
    ${{ github.event.release.tag_name || github.event.inputs.version || '1.20.0' }}

jobs:
  windows_x64:
    name: Download android onnxruntime lib
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download android onnxruntime lib
        shell: bash
        run: |
          version=${{ env.ONNXRUNTIME_VERSION }}
          wget -q https://repo1.maven.org/maven2/com/microsoft/onnxruntime/onnxruntime-android/$version/onnxruntime-android-$version.aar
          mv onnxruntime-android-$version.aar onnxruntime-android-$version.zip
          unzip onnxruntime-android-$version.zip
